Fix: Add a separate command to add environment variables to the lambda function

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -83,18 +83,22 @@ jobs:
           AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
 
       # Step 4: Deploy To AWS Lambda Function
-      - name: Deploy To AWS Lambda Function
-        run:
+      - name: Deploy from S3 to AWS Lambda with Environment Variables
+        run: |
           aws lambda update-function-code --function-name ${{ secrets.AWS_LAMBDA_FUNCTION_NAME }} --s3-bucket ${{ secrets.AWS_S3_BUCKET_NAME }} --s3-key api.zip
-        env:
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
-          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
+          sleep 10 # Add a 10-second delay
 
-      # Step 5: Add environment variables to the Lambda function
-      - name: Deploy To AWS Lambda Function
-        run:
-          aws lambda update-function-configuration --function-name ${{ secrets.AWS_LAMBDA_FUNCTION_NAME }} --environment "Variables={API_KEY='${{ secrets.API_KEY }}',DB_HOST='${{ secrets.DB_HOST }}'}"
+          retry_count=0
+          max_retries=5
+          while true; do
+            aws lambda update-function-configuration --function-name ${{ secrets.AWS_LAMBDA_FUNCTION_NAME }} --environment "Variables={API_KEY='${{ secrets.API_KEY }}',DB_HOST='${{ secrets.DB_HOST }}'}" && break
+            if [ $retry_count -ge $max_retries ]; then
+              echo "Max retries reached. Failed to update function configuration."
+              exit 1
+            fi
+            retry_count=$((retry_count + 1))
+            sleep 5 # Add a 5-second delay between retries
+          done
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
